version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - '5432:5432'